Update CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,15 +53,16 @@ jobs:
         fi
 
     - name: Run tests in Docker
+      continue-on-error: true
       env:
         BASE_URL: ${{ vars.BASE_URL }}
-        AUTH_USER: ${{ secrets.AUTH_USER }}
+        AUTH_USER_NAME: ${{ secrets.AUTH_USER_NAME }}
         AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
       run: |
         mkdir -p reports
         docker run --rm \
           -e BASE_URL="$BASE_URL" \
-          -e AUTH_USER="$AUTH_USER" \
+          -e AUTH_USER_NAME="$AUTH_USER_NAME" \
           -e AUTH_PASSWORD="$AUTH_PASSWORD" \
           -v ${{ github.workspace }}/reports:/tests/reports \
           api-tests ./run.sh
@@ -82,3 +83,16 @@ jobs:
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: allure-report
+
+    - name: Send Teams Notification
+      if: always()   # send even if tests fail
+      run: |
+          MESSAGE="API Tests Run Completed. \nAllure Report:
+             https://alexkaminskiy.github.io/api-automation-tests"
+
+              curl -H "Content-Type: application/json" \
+                  -d "{\"text\": \"${MESSAGE}\"}" \
+                  ${{ secrets.TEAMS_WEBHOOK_URL }}
+    
+    - name: Cleanup
+      run: docker rm -f locust-master worker-1 worker-2 worker-3 || true
